name: Build AniWRT

on:
  workflow_dispatch:
    inputs:
      resources:
        description: "Select resources (e.g., openwrt:23.05.4, immortalwrt:23.05.3)"
        required: true
        default: "openwrt:23.05.4"
      rootfs_partsize:
        description: "Specify ROOTFS_PARTSIZE in MB"
        required: true
        default: "256"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: Parse resources
        id: parse_resources
        run: |
          resources="${{ github.event.inputs.resources }}"
          DISTRO="${resources%%:*}"
          VERSION="${resources##*:}"
          echo "DISTRO=${DISTRO}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Download ImageBuilder
        run: |
          wget https://downloads.${{ env.DISTRO }}.org/releases/${{ env.VERSION }}/targets/armsr/armv8/${{ env.DISTRO }}-imagebuilder-${{ env.VERSION }}-armsr-armv8.Linux-x86_64.tar.xz -O imagebuilder.tar.xz
          mkdir imagebuilder
          tar -xf imagebuilder.tar.xz -C imagebuilder --strip-components=1

      - name: Build image
        run: |
          cd imagebuilder
          make image PROFILE="generic" ROOTFS_PARTSIZE=${{ github.event.inputs.rootfs_partsize }}

      - name: List output files
        run: |
          find imagebuilder/bin/targets -type f

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.DISTRO }}-${{ env.VERSION }}
          release_name: ${{ env.DISTRO }} ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload image to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: imagebuilder/bin/targets/armsr/armv8/generic-ext4-combined.img.gz # Update based on output
          asset_name: ${{ env.DISTRO }}-${{ env.VERSION }}-armsr-armv8-generic-ext4-combined.img.gz
          asset_content_type: application/octet-stream
